### ISSUE TITLE
cool dmenu

### ISSUE THREAD

**Issue by guoruibiao** [kootenpv/emoji-picker#1]
```shell
dmenu -f -i -l 5 | cut -d ' ' -f 1
```

It's awesome. 👍

I tried to make it work on my MBP, using `pbcopy` and `pbpaste` to replace the `calling of xclip`.
but I cannot find the suitable menu selection such as `dmenu`...

**Comment by kootenpv** [comment]
You motivated me to make a new version that's cross platform. Please pull again and see if it works for you?

**Comment by guoruibiao** [comment]
#### about `just`
It seems something wrong happened on my MBP, and the code below doesn't work for the directory `/tmp/emoji_picker/` with the version of Python `python3.7`
```python
just.write("\n".join(extras + results) + "\n", "~/emojis2.txt")
```

some hardcode at `main.py` 😆 

#### the `ANR` question
After i typed `python3 main.py`,  a popped window comes, but whatever i typed anything, nothing happened. FYI, my machine details as follows.
```shell
uname -a
Darwin localhost 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
python3 --version
Python 3.7.3
```

**Comment by kootenpv** [comment]
@guoruibiao Thanks for trying! Is there any output in the terminal when trying to run both the download_emotes and the main?

**Comment by guoruibiao** [comment]
nope, exactly.

By the way, the job you have done is pretty cool, and i will keep watching it. 
The comment of GitHub issue seems not very instant, should i have your public chatting account?

FB, Wechat or something others will be all right. Happy to see you, dude!
